#!/usr/bin/env python3
"""Pull one archived run from Spaces to Drive, and re-verify it there.

The PI's act, by design (Item 3, leg 4). The droplet uploads and verifies; this
script brings the bundle down onto the machine that has Drive File Stream mounted
and checks it *again, on that machine*, against the ``SHA256SUMS`` that travelled
with it.

The second verification is the reason the script exists at all. The droplet
already proved that what is in the bucket matches what was on its disk. What
nobody has yet proved is that what lands in ``G:\\My Drive\\...`` matches what is
in the bucket — and a sync client writing into a virtual filesystem is exactly
the kind of place a file gets truncated, deduplicated, or quietly not written.
So verification runs against the **destination path**, reading the bytes back
through Drive, not against the download stream in flight.

**Standalone on purpose.** It imports nothing from ``g3o``: it has to run on a
machine that may have no checkout, no virtualenv, and no pipeline installed —
only Python and ``boto3``::

    pip install boto3
    python pull_run_archive.py --run-id r20260813T101500Z-9c2f \\
        --destination s3://g3o-archive/runs \\
        --dest "G:/My Drive/G3O/run-archive"

    # re-verify a copy that is already in Drive, downloading nothing:
    python pull_run_archive.py --run-id r2026... --dest "G:/My Drive/..." --verify-only

Credentials come from ``SPACES_KEY`` / ``SPACES_SECRET`` and the endpoint from
``SPACES_ENDPOINT``, never from arguments — an argument lands in shell history
and in every process listing.

Exit codes: 0 verified · 1 downloaded but verification failed · 2 could not run.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path
from urllib.parse import urlsplit

SHA256SUMS_FILENAME = "SHA256SUMS"
CHUNK_BYTES = 1024 * 1024

EXIT_OK = 0
EXIT_VERIFY_FAILED = 1
EXIT_REFUSED = 2


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while True:
            chunk = handle.read(CHUNK_BYTES)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def parse_sha256sums(path: Path) -> list[tuple[str, str]]:
    """``[(sha256, relative path)]`` from a coreutils-format sums file.

    Accepts both ``hash  path`` (text mode) and ``hash *path`` (binary mode) so a
    file regenerated by ``sha256sum`` on any machine still reads.
    """
    rows: list[tuple[str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        digest, name = parts[0], parts[1].lstrip("*").strip()
        rows.append((digest, name))
    return rows


def make_client(endpoint: str | None, region: str | None):
    try:
        import boto3
    except ImportError:
        sys.stderr.write(
            "boto3 is not installed. `pip install boto3` — it is the only "
            "dependency this script has beyond the standard library.\n"
        )
        raise SystemExit(EXIT_REFUSED) from None
    endpoint = endpoint or os.environ.get("SPACES_ENDPOINT")
    if not endpoint:
        sys.stderr.write(
            "no endpoint: set SPACES_ENDPOINT (e.g. https://sfo3.digitaloceanspaces.com) "
            "or pass --endpoint.\n"
        )
        raise SystemExit(EXIT_REFUSED)
    key = os.environ.get("SPACES_KEY")
    secret = os.environ.get("SPACES_SECRET")
    if not (key and secret):
        sys.stderr.write(
            "SPACES_KEY / SPACES_SECRET are unset. They are read from the "
            "environment only — never passed as arguments.\n"
        )
        raise SystemExit(EXIT_REFUSED)
    return boto3.client(
        "s3",
        endpoint_url=endpoint,
        region_name=region or os.environ.get("SPACES_REGION") or "us-east-1",
        aws_access_key_id=key,
        aws_secret_access_key=secret,
    )


def list_keys(client, bucket: str, prefix: str) -> list[str]:
    keys: list[str] = []
    token = None
    while True:
        kwargs = {"Bucket": bucket, "Prefix": prefix}
        if token:
            kwargs["ContinuationToken"] = token
        page = client.list_objects_v2(**kwargs)
        keys.extend(item["Key"] for item in page.get("Contents", ()))
        if not page.get("IsTruncated"):
            return sorted(keys)
        token = page.get("NextContinuationToken")


def download(client, bucket: str, key: str, dest: Path) -> None:
    """Download one object, atomically at the destination.

    Via a temp file in the same directory and :func:`os.replace`, so an
    interrupted pull — a laptop that sleeps mid-sync — never leaves a truncated
    file under the real name for the verification pass to bless.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_name(dest.name + ".part")
    client.download_file(bucket, key, str(tmp))
    os.replace(tmp, dest)


def verify_tree(root: Path) -> tuple[int, list[str]]:
    """Re-hash every file listed in ``root/SHA256SUMS``. Returns (checked, problems)."""
    sums = root / SHA256SUMS_FILENAME
    if not sums.is_file():
        return 0, [f"{sums} is missing — the bundle carries no checksums to verify against."]
    problems: list[str] = []
    rows = parse_sha256sums(sums)
    for expected, relpath in rows:
        path = root.joinpath(*relpath.split("/"))
        if not path.is_file():
            problems.append(f"MISSING  {relpath}")
            continue
        try:
            observed = sha256_file(path)
        except OSError as exc:
            problems.append(f"UNREADABLE {relpath}: {exc}")
            continue
        if observed != expected:
            problems.append(f"MISMATCH {relpath}: expected {expected[:16]}…, got {observed[:16]}…")
    return len(rows), problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="pull_run_archive.py",
        description=(
            "Pull one archived G3O run from Spaces into a local (Drive) folder and "
            "re-verify its SHA256SUMS there."
        ),
    )
    parser.add_argument("--run-id", required=True, help="The run to pull.")
    parser.add_argument(
        "--dest", required=True,
        help="Local destination root; the run lands in <dest>/<run-id>/. Point it "
             "at the Drive File Stream folder.",
    )
    parser.add_argument(
        "--destination", default=None, metavar="URI",
        help="s3://bucket/prefix the droplet uploaded to. Required unless --verify-only.",
    )
    parser.add_argument("--endpoint", default=None, help="Defaults to $SPACES_ENDPOINT.")
    parser.add_argument("--region", default=None, help="Defaults to $SPACES_REGION.")
    parser.add_argument(
        "--verify-only", action="store_true",
        help="Skip the download and re-verify the copy already in --dest.",
    )
    parser.add_argument(
        "--overwrite", action="store_true",
        help="Re-download objects that are already present locally. Off by "
             "default so an interrupted pull resumes cheaply.",
    )
    args = parser.parse_args(argv)

    root = Path(args.dest).expanduser() / args.run_id

    if not args.verify_only:
        if not args.destination:
            sys.stderr.write("--destination is required unless --verify-only is passed.\n")
            return EXIT_REFUSED
        parts = urlsplit(args.destination)
        if parts.scheme not in ("s3", "spaces") or not parts.netloc:
            sys.stderr.write(f"--destination must be s3://bucket/prefix, got {args.destination!r}.\n")
            return EXIT_REFUSED
        bucket = parts.netloc
        prefix = parts.path.strip("/")
        remote_prefix = f"{prefix}/{args.run_id}/" if prefix else f"{args.run_id}/"

        client = make_client(args.endpoint, args.region)
        keys = list_keys(client, bucket, remote_prefix)
        if not keys:
            sys.stderr.write(
                f"nothing under s3://{bucket}/{remote_prefix} — check the run id and "
                f"the --destination prefix.\n"
            )
            return EXIT_REFUSED
        print(f"Pulling {len(keys)} object(s) from s3://{bucket}/{remote_prefix}")
        for i, key in enumerate(keys, start=1):
            relpath = key[len(remote_prefix):]
            dest = root.joinpath(*relpath.split("/"))
            if dest.is_file() and not args.overwrite:
                print(f"  [{i}/{len(keys)}] have {relpath}")
                continue
            print(f"  [{i}/{len(keys)}] {relpath}")
            download(client, bucket, key, dest)

    print(f"\nVerifying {root / SHA256SUMS_FILENAME} against the files in {root}")
    checked, problems = verify_tree(root)
    if problems:
        print(f"\nFAILED — {len(problems)} problem(s) out of {checked} file(s):")
        for problem in problems[:50]:
            print(f"  {problem}")
        if len(problems) > 50:
            print(f"  … and {len(problems) - 50} more")
        print(
            "\nThe copy in the destination does not match the checksums that "
            "travelled with it. Re-pull with --overwrite; if it fails again, the "
            "bucket copy is suspect and the droplet's own archive log is the next "
            "thing to read."
        )
        return EXIT_VERIFY_FAILED
    print(f"\nOK — {checked} file(s) verified by sha256 in {root}.")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
